version: '3'

services:
  web-server:
    container_name: web-server
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php-runner

  php-runner:
    container_name: php-runner
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
