version: '3'

services:
  web-server:
    container_name: web-server
    build:
      context: build/nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www

  php-runner:
    container_name: php-runner
    build:
      context: build/php-fpm
    volumes:
      - ./src:/var/www
