version: '3'

services:
  web-server:
    container_name: web-server
    build:
      context: docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
    depends_on:
      - php-runner

  php-runner:
    container_name: php-runner
    build:
      context: docker/php-fpm
    volumes:
      - ./src:/var/www
